// Package producer drives the load-generation pipeline:
//
//   - N "builder" goroutines pull ticks from the rate bucket, ask the mixer
//     for the next pattern, build a dnstap envelope, marshal it to bytes,
//     and push the bytes onto a buffered channel.
//   - One "sender" goroutine pops bytes off the channel and writes them via
//     the Sink. The framestream Writer is not safe for concurrent callers
//     so the sender stays single-goroutine.
//
// This split keeps the I/O serialized while letting the CPU-bound work
// (DNS packing + proto.Marshal + RNG-driven query construction) parallelize
// across cores. Single-threaded build was the previous throughput cap.
//
// Beacon traffic runs on its own time-driven goroutine and pushes envelopes
// onto the same send channel, bypassing the rate bucket.
package producer

import (
	"context"
	"fmt"
	"runtime"
	"sync"
	"sync/atomic"
	"time"

	"github.com/linkdata/edm-loadgen/internal/dns"
	"github.com/linkdata/edm-loadgen/internal/dnstap"
	"github.com/linkdata/edm-loadgen/internal/mix"
	"github.com/linkdata/edm-loadgen/internal/pattern"
	"github.com/linkdata/edm-loadgen/internal/rate"
	"github.com/linkdata/edm-loadgen/internal/state"
)

// Producer is a long-running orchestrator that drains the rate bucket at
// the configured QPS and writes envelopes to a Sink.
//
// Each worker owns its own Mixer (and through that, its own pattern
// instances with private RNG and exfil state). This avoids any shared lock
// on the build hot path: workers contend only on the bucket's tick channel
// and the marshalled-frame queue.
type Producer struct {
	st      *state.State
	domains []string
	beacon  *pattern.Beacon
	sink    byteSender
	bucket  *rate.Bucket
	workers int
	frames  *frameBufferPool
}

type byteSender interface {
	SendBytes([]byte) error
}

// sendItem is the unit traversing the pipeline: a pre-marshalled pooled frame
// plus the pattern name it was generated by (for counter attribution).
type sendItem struct {
	pattern string
	frame   []byte
}

const (
	initialFrameBufferCap = 512
	maxPooledFrameCap     = 64 * 1024
)

type frameBufferPool struct {
	pool sync.Pool
}

func newFrameBufferPool() *frameBufferPool {
	p := &frameBufferPool{}
	p.pool.New = func() any {
		return make([]byte, 0, initialFrameBufferCap)
	}
	return p
}

func (p *frameBufferPool) get() []byte {
	return p.pool.Get().([]byte)[:0]
}

func (p *frameBufferPool) put(buf []byte) {
	if cap(buf) > maxPooledFrameCap {
		return
	}
	p.pool.Put(buf[:0])
}

// New constructs a Producer. workers <= 0 means "default to GOMAXPROCS".
// domains is the pre-loaded top-domains list shared across all workers'
// Background generators. beacon stays single-instance because it has its
// own time-driven goroutine with no concurrent callers.
func New(st *state.State, domains []string, beacon *pattern.Beacon, snk byteSender, workers int) *Producer {
	if workers <= 0 {
		workers = runtime.GOMAXPROCS(0)
	}
	return &Producer{
		st:      st,
		domains: domains,
		beacon:  beacon,
		sink:    snk,
		bucket:  rate.NewBucket(&st.QPS),
		workers: workers,
		frames:  newFrameBufferPool(),
	}
}

// Run starts the worker / sender / beacon / publish-rate goroutines and
// blocks until ctx is cancelled.
func (p *Producer) Run(ctx context.Context) error {
	defer p.bucket.Close()

	// The send channel decouples the CPU-bound build path from the I/O-
	// bound sender. Capacity scales with worker count so a momentary slow
	// sender doesn't immediately stall every worker.
	queue := make(chan sendItem, p.workers*8)

	bgCtx, cancelBg := context.WithCancel(ctx)
	defer cancelBg()
	go p.runBeacon(bgCtx, queue)
	go p.publishRate(bgCtx)

	// Spin up N builders, each with its own Mixer (and thus its own pattern
	// instances and private RNG state).
	var wg sync.WaitGroup
	for i := 0; i < p.workers; i++ {
		m, err := mix.NewWithPatterns(p.st, p.domains, uint64(i+1)<<32)
		if err != nil {
			return fmt.Errorf("producer: build mixer %d: %w", i, err)
		}
		wg.Add(1)
		go func(m *mix.Mixer) {
			defer wg.Done()
			p.buildLoop(ctx, m, queue)
		}(m)
	}

	// Sender goroutine. Closes when builders are done AND beacon is done
	// (cancelBg above + wg below).
	sendDone := make(chan struct{})
	go func() {
		defer close(sendDone)
		for item := range queue {
			if err := p.sink.SendBytes(item.frame); err != nil {
				p.frames.put(item.frame)
				continue
			}
			bumpCounter(p.st, item.pattern)
			p.frames.put(item.frame)
		}
	}()

	wg.Wait()    // builders exited (bucket closed or ctx done)
	cancelBg()   // stop beacon + publishRate
	close(queue) // tell sender no more items
	<-sendDone   // sender drained and exited
	return ctx.Err()
}

// buildLoop is one builder. It owns mixer (per-worker) and pulls ticks
// from the shared bucket, pushing envelopes onto the shared queue.
func (p *Producer) buildLoop(ctx context.Context, mixer *mix.Mixer, queue chan<- sendItem) {
	var builder frameBuilder
	for p.bucket.Wait() {
		if ctx.Err() != nil {
			return
		}
		if !p.st.IsRunning() {
			continue
		}
		gen := mixer.Pick()
		if gen == nil {
			continue
		}
		q, err := gen.Next(ctx)
		if err != nil {
			if ctx.Err() != nil {
				return
			}
			continue
		}
		buf := p.frames.get()
		frame, err := builder.buildAppend(q, buf)
		if err != nil {
			p.frames.put(buf)
			continue
		}
		select {
		case queue <- sendItem{pattern: gen.Name(), frame: frame}:
		case <-ctx.Done():
			p.frames.put(frame)
			return
		}
	}
}

// runBeacon emits beacon queries on its own time-driven cadence, independent
// of the QPS bucket. Honours the beacon mix weight: when zero, the beacon is
// silent. Pushes onto the same send queue as the workers.
func (p *Producer) runBeacon(ctx context.Context, queue chan<- sendItem) {
	var builder frameBuilder
	for {
		if atomic.LoadInt32(&p.st.Mix.Beacon) <= 0 {
			select {
			case <-ctx.Done():
				return
			case <-time.After(time.Second):
			}
			continue
		}
		q, err := p.beacon.Next(ctx)
		if err != nil {
			return
		}
		if !p.st.IsRunning() {
			continue
		}
		buf := p.frames.get()
		frame, err := builder.buildAppend(q, buf)
		if err != nil {
			p.frames.put(buf)
			continue
		}
		select {
		case queue <- sendItem{pattern: "beacon", frame: frame}:
		case <-ctx.Done():
			p.frames.put(frame)
			return
		}
	}
}

// publishRate samples the bucket's observed rate every 500ms and writes it
// to st.ObservedQPS.
func (p *Producer) publishRate(ctx context.Context) {
	t := time.NewTicker(500 * time.Millisecond)
	defer t.Stop()
	for {
		select {
		case <-ctx.Done():
			atomic.StoreInt32(&p.st.ObservedQPS, 0)
			return
		case <-t.C:
			atomic.StoreInt32(&p.st.ObservedQPS, p.bucket.Rate())
		}
	}
}

// buildFrame turns a pattern.Query into a marshalled dnstap frame. Pure
// CPU work — runs on the builder goroutines, off the send hot path.
func buildFrame(q pattern.Query) ([]byte, error) {
	var builder frameBuilder
	return builder.build(q)
}

type frameBuilder struct {
	dnsb dns.Builder
	tapb dnstap.ClientResponseBuilder
	id   uint16
	buf  []byte
}

func (b *frameBuilder) build(q pattern.Query) ([]byte, error) {
	frame, err := b.buildAppend(q, b.buf)
	if err != nil {
		return nil, err
	}
	b.buf = frame[:0]
	return frame, nil
}

func (b *frameBuilder) buildAppend(q pattern.Query, dst []byte) ([]byte, error) {
	b.id++
	dnsBytes, err := b.dnsb.Response(b.id, q.QName, q.QType, q.Answers)
	if err != nil {
		return nil, fmt.Errorf("producer: pack dns: %w", err)
	}
	frame, err := b.tapb.MarshalClientResponseAppend(dst, dnstap.Query{
		SrcIP: q.SrcIP,
		DstIP: q.DstIP,
		At:    q.At,
		DNS:   dnsBytes,
	})
	if err != nil {
		return nil, fmt.Errorf("producer: marshal: %w", err)
	}
	return frame, nil
}

func bumpCounter(st *state.State, name string) {
	switch name {
	case "background":
		atomic.AddInt64(&st.Sent.Background, 1)
	case "wellknown":
		atomic.AddInt64(&st.Sent.WellKnown, 1)
	case "dga":
		atomic.AddInt64(&st.Sent.DGA, 1)
	case "beacon":
		atomic.AddInt64(&st.Sent.Beacon, 1)
	case "fastflux":
		atomic.AddInt64(&st.Sent.FastFlux, 1)
	case "dyndns":
		atomic.AddInt64(&st.Sent.DynDNS, 1)
	case "exfil":
		atomic.AddInt64(&st.Sent.Exfil, 1)
	case "exotic":
		atomic.AddInt64(&st.Sent.Exotic, 1)
	case "evasion":
		atomic.AddInt64(&st.Sent.Evasion, 1)
	}
	atomic.AddInt64(&st.Sent.Total, 1)
}
